version: "2"
services:
  validate:
    build: .
    environment:
      - NODE_ENV=validate
    volumes:
      - ./input:/usr/src/app/input
      - ./output:/usr/src/app/output
  dev:
    build: .
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/usr/src/app
  test:
    build: .
    environment:
      - NODE_ENV=test
    volumes:
      - .:/usr/src/app
